### PR TITLE
Update abstract tests

### LINKED ISSUE #94: Eclipse: Abstract test superclasses in test-only packages are not exported by JPMS
For example, `net.imagej.ops2.features.tamura2.Tamura2dFeatureTest` extends `net.imagej.ops2.features.AbstractFeatureTest`. However, the package `net.imagej.ops2.features` is a test-only package and thus not exported in the `imagej-ops2` `module-info.java`.

This results in an exception when trying to run `Tamura2dFeatureTest` independently in Eclipse:

```
java.lang.reflect.InaccessibleObjectException: Unable to make public void net.imagej.ops2.features.AbstractFeatureTest.setup() accessible: module net.imagej.ops2 does not "exports net.imagej.ops2.features" to unnamed module @66498326
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at org.junit.platform.commons.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:1658)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

The simplest workaround would be to move any abstract test superclasses in test-only packages to a parent package that is known to be exported, e.g. `net.imagej.ops2`.

We know that a `module-info.java` in `src/test/java` is a non-started since it competes with that in `src/main/java`. I am curious if there is a way to have test-specific exports. It sounds like this is possible with [`--patch-module`](https://stackoverflow.com/a/46613986), which is maybe done automatically by maven/gradle?

### PR DESCRIPTION
**Pull request by hinerm**
Closes scijava/scijava#94

### CODE REVIEW

**Review by gselzer — COMMENTED** [review]
Thanks for making changes @hinerm!

I don't have much of a problem with the individual changes, and I appreciate that you did the minimum to make the build work.

I am a bit concerned, though, about the idea of putting all of the abstract tests in the top-level folder. My main concern is that this practice will likely conflict with the subpackage dependency rule reinstated in scijava/incubator#59, so conforming this rule will limit what we do with abstract classes in tests. But, I didn't see anything in this PR that would break the rules...

I also dislike the fact that we have to make this change for an IDE. I don't think I've had this issue in IntelliJ. Is there any way we could use `--patch-module` in the Eclipse configuration? 

Here is how surefire [patches the module](https://issues.apache.org/jira/browse/SUREFIRE-1420)

**Comment by ctrueden** [comment]
@gselzer I agree that this change is unfortunate, but it gets the build passing, and we need that now. How about this plan:

* Change this PR description to *not* close scijava/scijava#94.
* Leave scijava/scijava#94 open as a reminder to move the abstract test classes back where they belong, with a better solution.
* Change scijava/scijava#94 subject and summary to explain that this problem is Eclipse-specific, and that the work to be done is to somehow enable main module patching from Eclipse.

**Comment by gselzer** [comment]
> I agree that this change is unfortunate, but it gets the build passing, and we need that now

 Well, the build *is* passing, just not in Eclipse.

> How about this plan

That sounds fine, but are we really sure that the correct fix will take so long to implement?  It seems like you could just do something like [this](https://stackoverflow.com/questions/68501382/how-to-make-eclipse-run-patched-jre-modules-on-jdk9-with-the-patch-module-java); if that works, is there some way that we could save those args as state somewhere in JPMS projects?

**Comment by hinerm** [comment]
> Well, the build _is_ passing, just not in Eclipse.

It's unfortunate that it works in IntelliJ and not Eclipse, but I do think we should strive for IDE compatibility.

> My main concern is that this practice will likely conflict with the subpackage dependency rule reinstated in #59, so conforming this rule will limit what we do with abstract classes in tests.

Understandable. I checked out #59 and tested and confirmed these changes still pass there. I think that if you have a series of (sub)packages, `a.b.c`.. then I am not sure what scenario could arise that would be a problem that wouldn't also be problematic with `b` folded into `a`... e.g. a circular dependency between `b` and `c` would be a problem regardless right?

Also I like having the `AbstractFeatureTest` in the common, high-level `ops2` package since it is also extended by classes outside of the `features` package (i.e. `PolygonFeatureTest` in the `geom` subpackage).

> That sounds fine, but are we really sure that the correct fix will take so long to implement?

If it was for production code then I think it would be worth more investigation, but since it's just the tests and just for running manually in Eclipse I think we will get very minimal return on time invested, until a point where there is a demonstrable need to have `AbstractFeatureTest` in a distinct subpackage. I would be strongly against any mechanism that requires passing around eclipse configuration files or the equivalent, and my assumption is something like that would be required to add VM params to the run configurations automatically.

**Comment by hinerm** [comment]
>Well, the build is passing, just not in Eclipse.

@gselzer the tests also do not work for me in IntelliJ. On `main` @ https://github.com/scijava/incubator/commit/a245ba7e6a33241ec5d3d72e7c034b37791ab783 I get a:
```
java.lang.reflect.InaccessibleObjectException: Unable to make public void net.imagej.ops2.features.AbstractFeatureTest.setup() accessible: module net.imagej.ops2 does not "exports net.imagej.ops2.features" to unnamed module @10163d6
```

which goes away with this patch.

@ctrueden do you have any objections or can we merge?

**Review by ctrueden — APPROVED** [review]
This is a step forward for immediate development. We always have the flexibility to refactor any test-scope classes and packages; we're not boxing ourselves into any corners design-wise.

**Comment by hinerm** [comment]
oh good* news, `Tamura2dFeatureTest` *still* fails for me in IntelliJ with this branch, it just gives different error messages whether its run individually (see above error) or as part of "All Tests" from the `imagej-ops2` component, with:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 10000 out of bounds for length 10000
```
Everything passes from the command line. ☠️ 


*I've chosen to contextualize bad news as good news

**Comment by gselzer** [comment]
@ctrueden said:

> This is a step forward for immediate development. We always have the flexibility to refactor any test-scope classes and packages; we're not boxing ourselves into any corners design-wise.

Yes, good point. Thank you both for working on this!

@hinerm said:

> oh good* news, Tamura2dFeatureTest still fails for me in IntelliJ with this branch, it just gives different error messages whether its run individually (see above error) or as part of "All Tests" from the imagej-ops2 component, with:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 10000 out of bounds for length 10000
```

I'm pretty certain this is a bug in imglib2's `LoopBuilder`. I asked @maarzt about it at some point on Gitter, I'll try to find it.

EDIT: [Found it](https://gitter.im/imglib/imglib2?at=6192b8a898c13e755037646f)

**Comment by hinerm** [comment]
and I think I was wrong.. I cleaned and re-ran everything and the exception is consistently the AIOOBE it looks like. Yay!

**Comment by gselzer** [comment]
> and I think I was wrong.. I cleaned and re-ran everything and the exception is consistently the AIOOBE it looks like. Yay!



It's a shame that nobody (including myself) made progress on that bug, as far as I can remember. Not even an issue in imglib2...

**Pull request merged**
